// <auto-generated />
namespace TrashCollector1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class madesomechangesinreqularpikupanddetailsmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madesomechangesinreqularpikupanddetailsmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201812111954015_made some changes in reqular pikup and details model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
