// <auto-generated />
namespace TrashCollector1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedmodelsforusualpickupsspecialpickupsandsuspendaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmodelsforusualpickupsspecialpickupsandsuspendaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201812101721006_added models for usual pickups,special pickups and suspend account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
